import SwiftUI
import UniformTypeIdentifiers

/// Browser view for loading and viewing infographic JSON files
struct InfographicBrowserView: View {
    @State private var infographic: InteractiveInfographic?
    @State private var isLoading = false
    @State private var errorMessage: String?
    @State private var showFilePicker = false
    @State private var showInfographic = false
    
    var body: some View {
        ZStack {
            Color.bgPrimary.ignoresSafeArea()
            
            VStack(spacing: 0) {
                // Header
                HStack {
                    Text("Infographic")
                        .font(.largeTitle)
                        .fontWeight(.bold)
                        .foregroundColor(.textPrimary)
                    
                    Spacer()
                    
                    Button(action: { showFilePicker = true }) {
                        Image(systemName: "folder.badge.plus")
                            .font(.title2)
                            .foregroundColor(.accentPrimary)
                    }
                }
                .padding(.horizontal, Spacing.md)
                .padding(.top, Spacing.lg)
                .padding(.bottom, Spacing.sm)
                
                // Content
                if let infographic = infographic {
                    loadedView(infographic)
                } else if isLoading {
                    loadingView
                } else {
                    emptyView
                }
            }
        }
        .fileImporter(
            isPresented: $showFilePicker,
            allowedContentTypes: [UTType.json],
            allowsMultipleSelection: false
        ) { result in
            handleFileImport(result)
        }
        .fullScreenCover(isPresented: $showInfographic) {
            if let infographic = infographic {
                InfographicView(infographic: infographic)
            }
        }
        .preferredColorScheme(.dark)
    }
    
    // MARK: - Empty View
    
    private var emptyView: some View {
        VStack(spacing: Spacing.lg) {
            Image(systemName: "chart.bar.doc.horizontal")
                .font(.system(size: 64))
                .foregroundColor(.textSecondary)
            
            Text("No Infographic Loaded")
                .font(.title2)
                .fontWeight(.semibold)
                .foregroundColor(.textPrimary)
            
            Text("Load a JSON file generated by repo2interactive.py")
                .font(.body)
                .foregroundColor(.textSecondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, Spacing.xl)
            
            if let error = errorMessage {
                Text(error)
                    .font(.caption)
                    .foregroundColor(.error)
                    .padding()
                    .background(Color.error.opacity(0.1))
                    .cornerRadius(8)
            }
            
            Button(action: { showFilePicker = true }) {
                HStack(spacing: 8) {
                    Image(systemName: "folder.badge.plus")
                    Text("Load JSON File")
                }
                .font(.headline)
                .foregroundColor(.white)
                .frame(width: 200, height: 50)
                .background(Color.accentPrimary)
                .cornerRadius(12)
            }
            .padding(.top, Spacing.md)
            
            // Sample buttons (if you have bundled samples)
            VStack(spacing: Spacing.sm) {
                Text("Or try a sample:")
                    .font(.caption)
                    .foregroundColor(.textTertiary)
                
                HStack(spacing: Spacing.sm) {
                    sampleButton("California Law Chatbot", filename: "California-Law-Chatbot_interactive")
                    sampleButton("HTTPie CLI", filename: "cli_interactive")
                }
            }
            .padding(.top, Spacing.lg)
        }
    }
    
    private func sampleButton(_ title: String, filename: String) -> some View {
        Button(action: { loadSample(filename) }) {
            Text(title)
                .font(.subheadline)
                .foregroundColor(.textPrimary)
                .padding(.horizontal, 16)
                .padding(.vertical, 10)
                .background(Color.bgTertiary)
                .cornerRadius(8)
                .overlay(
                    RoundedRectangle(cornerRadius: 8)
                        .stroke(Color.bgTertiary, lineWidth: 1)
                )
        }
    }
    
    // MARK: - Loading View
    
    private var loadingView: some View {
        VStack(spacing: Spacing.md) {
            ProgressView()
                .progressViewStyle(CircularProgressViewStyle(tint: .accentPrimary))
                .scaleEffect(1.5)
            
            Text("Loading infographic...")
                .font(.body)
                .foregroundColor(.textSecondary)
        }
    }
    
    // MARK: - Loaded View
    
    private func loadedView(_ infographic: InteractiveInfographic) -> some View {
        ScrollView {
            VStack(alignment: .leading, spacing: Spacing.md) {
                // Info card
                VStack(alignment: .leading, spacing: Spacing.sm) {
                    HStack {
                        Image(systemName: "checkmark.circle.fill")
                            .foregroundColor(.success)
                        Text("Infographic Loaded")
                            .font(.headline)
                            .foregroundColor(.textPrimary)
                    }
                    
                    Divider()
                        .background(Color.bgTertiary)
                    
                    infoRow("Repository", value: infographic.repoName)
                    infoRow("Phases", value: "\(infographic.root.children.count)")
                    infoRow("Generated", value: formatDate(infographic.generatedAt))
                    
                    if let overview = infographic.pipelineOverview {
                        VStack(alignment: .leading, spacing: 4) {
                            Text("Pipeline Overview")
                                .font(.caption)
                                .foregroundColor(.textTertiary)
                            Text(overview)
                                .font(.subheadline)
                                .foregroundColor(.textSecondary)
                        }
                        .padding(.top, Spacing.xs)
                    }
                }
                .padding()
                .background(Color.bgSecondary)
                .cornerRadius(12)
                
                // View button
                Button(action: { showInfographic = true }) {
                    HStack {
                        Image(systemName: "eye.fill")
                        Text("View Infographic")
                    }
                    .font(.headline)
                    .foregroundColor(.white)
                    .frame(maxWidth: .infinity)
                    .frame(height: 50)
                    .background(Color.accentPrimary)
                    .cornerRadius(12)
                }
                
                // Load different file
                Button(action: { showFilePicker = true }) {
                    HStack {
                        Image(systemName: "folder.badge.plus")
                        Text("Load Different File")
                    }
                    .font(.subheadline)
                    .foregroundColor(.accentPrimary)
                    .frame(maxWidth: .infinity)
                    .frame(height: 44)
                    .background(Color.bgSecondary)
                    .cornerRadius(10)
                    .overlay(
                        RoundedRectangle(cornerRadius: 10)
                            .stroke(Color.accentPrimary.opacity(0.3), lineWidth: 1)
                    )
                }
            }
            .padding()
        }
    }
    
    private func infoRow(_ label: String, value: String) -> some View {
        HStack {
            Text(label)
                .font(.subheadline)
                .foregroundColor(.textSecondary)
            Spacer()
            Text(value)
                .font(.subheadline)
                .foregroundColor(.textPrimary)
        }
    }
    
    // MARK: - Actions
    
    private func handleFileImport(_ result: Result<[URL], Error>) {
        switch result {
        case .success(let urls):
            guard let url = urls.first else { return }
            loadFromURL(url)
            
        case .failure(let error):
            errorMessage = "Failed to select file: \(error.localizedDescription)"
        }
    }
    
    private func loadFromURL(_ url: URL) {
        isLoading = true
        errorMessage = nil
        
        // Start accessing security-scoped resource
        guard url.startAccessingSecurityScopedResource() else {
            errorMessage = "Cannot access file"
            isLoading = false
            return
        }
        
        defer { url.stopAccessingSecurityScopedResource() }
        
        do {
            let data = try Data(contentsOf: url)
            if let loaded = InteractiveInfographic.load(from: data) {
                infographic = loaded
            } else {
                errorMessage = "Invalid JSON format. Make sure the file was generated by repo2interactive.py"
            }
        } catch {
            errorMessage = "Failed to load file: \(error.localizedDescription)"
        }
        
        isLoading = false
    }
    
    private func loadSample(_ filename: String) {
        isLoading = true
        errorMessage = nil
        
        if let loaded = InteractiveInfographic.load(from: filename) {
            infographic = loaded
        } else {
            errorMessage = "Sample file '\(filename).json' not found in bundle"
        }
        
        isLoading = false
    }
    
    private func formatDate(_ dateString: String) -> String {
        // Simple date formatting - just return the date part
        if dateString.contains("T") {
            return String(dateString.split(separator: "T").first ?? Substring(dateString))
        }
        return dateString
    }
}

#Preview {
    InfographicBrowserView()
}
